export { ideaService } from './ideaService'
export { commentService } from './commentService'
export { userService } from './userService'
export { teamService } from './teamService'
export { adminService } from './supabaseAdminService'

export type { IIdeaService } from './ideaService'
export type { ICommentService } from './commentService'
export type { IUserService } from './userService'
export type { ITeamService } from './teamService'
export type { IAdminService } from './IAdminService'
export type { Tag } from '@/lib/types/tag'
export type { Badge } from '@/lib/types/badge'
export type { UserBadge } from '@/lib/types/userBadge'
export type { MediaAsset } from '@/lib/types/mediaAsset'
